# This file contains the configuration for the 'local' Spring profile, which is
# used to connect the application to a LocalStack container.
# This profile is activated by passing a command-line argument to the application.

# Standard LocalStack endpoint URL
aws.endpoint=http://localhost:4566
