spring.application.name=BulkProductsUpload
## SERVER CONFIG
server.port=8080

## AWS CONFIG
aws.region=ap-southeast-1
aws.s3.bucket=your-product-bucket
aws.dynamodb.table=Products

## LOCAL FILE SIZE LIMITS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB

## LOGGING
logging.level.root=INFO
logging.level.com.ankur=DEBUG
