spring.application.name=BulkProductsUpload
## SERVER CONFIG
server.port=8080

## LOCAL FILE SIZE LIMITS
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=500MB

## LOGGING
logging.level.root=INFO
logging.level.com.ankur=DEBUG

aws.region=${AWS_REGION:ap-southeast-2}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:bulk-upload-product-images}
